apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sandboxfleet-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sandboxfleet-controller
subjects:
  - kind: ServiceAccount
    name: sandboxfleet-controller
    namespace: sandboxfleet-system
