apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manager/namespace.yaml
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml
  - crd/sandboxpools.yaml
  - crd/sandboxes.yaml
  - crd/sandboxsnapshots.yaml
  - manager/deployment.yaml
